server:
  port: 9010
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: 123456
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat
spring:
  application:
    name: register
eureka:
  instance:
     hostname: localhost
     securePort: ${server.port}
     securePortEnabled: true
     nonSecurePortEnabled: false
     secureVirtualHostName: ${spring.application.name}
     homePageUrl: https://${eureka.instance.hostname}:${server.port}/
     statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
     metadataMap:
         hostname : ${eureka.instance.hostname}
         securePort: ${server.port}
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
          defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
#logging:
#  level:
#    root: debug

logging.file: /opt/micro/log/regist.log
logging.level.root: info

#logging.file: E:\log\register.log
#logging.level.root: INFO

