server:
  port: 9083
#server.port: 9090
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: 123456
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat
server.ssl.enabled: true
spring:
  application:
    name: Service-File
#  zipkin:
#      base-url: http://10.10.8.2:9050
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/certdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hzq123
    druid:
      driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
       defaultZone: https://localhost:9010/eureka/
       healthcheck:
           enabled: true
  instance:
      hostname: localhost
      preferIpAddress: false
      securePortEnabled: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
      healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
endpoints:
  health:
    sensitive: false
    enabled: false
management:
  security:
    enabled: true
ribbon:
    IsSecure: true
    eureka:
        enabled: true
logging:
  level:
    root: info

spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto: update

logging.level.root: info

fzk.port: 8760
file.issave: false
file.encry.algorithm: AES
file.encry.key: hKrBL1SrZm7Pw==Q
##服务器上应用路径
file.Upload.path: /opt/micro/secret
file.encry.keyfile: /opt/micro/secret
logging.file: /opt/micro/log/service_file.log

##本地开发文件保存路径
#file.Upload.path: E:\secret
#file.encry.keyfile: E:\secret
#logging.file: E:\log\upfile.log
